# Generated by Django 5.1.4 on 2025-01-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="active_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
