# Generated by Django 5.1.4 on 2025-02-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0002_election_active_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="age_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("18-25", "18-25"),
                    ("26-35", "26-35"),
                    ("36-45", "36-45"),
                    ("46-60", "46-60"),
                    ("60+", "60+"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Prefer not to say", "Prefer not to say"),
                ],
                default="Prefer not to say",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
