# Generated by Django 5.1.4 on 2025-02-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0003_customuser_age_group_customuser_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
