# Generated by Django 5.1.4 on 2025-02-23 00:33

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0004_customuser_city_customuser_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
    ]
