# Generated by Django 5.1.4 on 2025-02-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0005_alter_customuser_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="city",
        ),
        migrations.AddField(
            model_name="election",
            name="total_registered_voters",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
