# Generated by Django 5.1.4 on 2025-02-27 08:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0006_remove_customuser_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="election",
            name="total_registered_voters",
        ),
    ]
