# Generated by Django 5.1.4 on 2025-02-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0007_remove_election_total_registered_voters"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="total_voters",
            field=models.IntegerField(default=0),
        ),
    ]
